environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
version: 0.0.{build}
image:
    - Ubuntu
    - Visual Studio 2019
init:
    - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 70 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - sh: sudo apt install -y xorg-dev libglu1-mesa-dev libgl1-mesa-dev
before_build:
    - sh: sudo bash init.sh
    - ps: ./init.ps1
build_script:
    - sh: cmake .
    - cmd: cmake -A x64 -B . -DPGO=GENPROFILE
    - ps: cmake --build . --config Release
    - ps: .\run_pgo.bat
    - cmd: cmake -A x64 -B . -DPGO=USEPROFILE
    - cmake --build . --config Release 
    - cpack
test_script:
    - ctest --output-on-failure --build-config Release
artifacts:
    - path: 'packages\**\*.sh'
      name: linux_installer
      type: zip
    - path: 'packages\**\*.exe'
      name: windows_installer
      type: zip