environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
version: 0.0.{build}
image:
    - Visual Studio 2017
    - Ubuntu
init:
    - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 70 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - sh: sudo apt install -y flex
    - sh: wget -O /tmp/llnextgen.deb "https://os.ghalkes.nl/LLnextgen/releases/llnextgen_0.5.5-1_amd64.deb"
    - sh: sudo apt install -y /tmp/llnextgen.deb
    - ps: Invoke-WebRequest -Uri "https://netix.dl.sourceforge.net/project/gnuwin32/flex/2.5.4a-1/flex-2.5.4a-1-bin.zip" -OutFile "$env:TEMP\flex.zip" -ErrorAction SilentlyContinue
    - ps: Expand-Archive "$env:TEMP\flex.zip" -DestinationPath "$env:TEMP\flex"
    - ps: Invoke-WebRequest -Uri "https://os.ghalkes.nl/LLnextgen/releases/LLnextgen-w64-0.5.5.zip" -OutFile "$env:TEMP\LLnextgen.zip" -ErrorAction SilentlyContinue
    - ps: Expand-Archive "$env:TEMP\LLnextgen.zip" -DestinationPath "$env:TEMP\LLnextgen"
    - ps: Invoke-Expression "$env:TEMP\flex\bin\flex --version"
    - ps: Invoke-Expression "$env:TEMP\LLnextgen\LLnextgen\LLnextgen --version"
before_build:
    - cmake .
build_script:
    - cmake --build . --config Release
    - cpack
test_script:
    - ps: ctest --output-on-failure
artifacts:
    - path: 'packages\**\*.sh'
      name: linux_installer
      type: zip
    - path: 'packages\**\*.exe'
      name: windows_installer
      type: zip